version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo "Building Docker images..."
      - docker build -t $ECR_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/laravel-app:$IMAGE_TAG -f Dockerfile .
      - docker build -t $ECR_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/laravel-node:$IMAGE_TAG -f Dockerfile.node .
      - docker build -t $ECR_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/laravel-nginx:$IMAGE_TAG -f Dockerfile.nginx .
  post_build:
    commands:
      - echo "Pushing Docker images..."
      - docker push $ECR_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/laravel-app:$IMAGE_TAG
      - docker push $ECR_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/laravel-node:$IMAGE_TAG
      - docker push $ECR_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/laravel-nginx:$IMAGE_TAG

      - echo "Creating imagedefinitions.json..."
      - |
        cat > imagedefinitions.json <<EOF
        [
          {
            "name": "laravel-app",
            "imageUri": "$ECR_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/laravel-app:$IMAGE_TAG"
          },
          {
            "name": "laravel-node",
            "imageUri": "$ECR_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/laravel-node:$IMAGE_TAG"
          },
          {
            "name": "laravel-nginx",
            "imageUri": "$ECR_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/laravel-nginx:$IMAGE_TAG"
          }
        ]
        EOF

artifacts:
  files:
    - imagedefinitions.json
    - taskdef.json
    - appspec.yml
