FROM public.ecr.aws/docker/library/nginx:alpine

# Copy custom Nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy Laravel public files
WORKDIR /var/www
COPY . .

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
