FROM public.ecr.aws/docker/library/node:20

WORKDIR /var/www

COPY package.json yarn.lock ./
RUN yarn install

COPY . .

# Build production assets
RUN yarn build

# No need for yarn dev in production
CMD ["yarn", "start"]
